# Build release

name: Build release


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci

      - name: Build release
        run: npm run build
        env:
          NODE_ENV: production
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Create a Release in a GitHub Action
        uses: comnoco/create-release-action@v2.0.5
        with:
          tag: ${{ steps.previoustag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*
          name: Release ${{ steps.previoustag.outputs.tag }}
          body: |
            Release ${{ steps.previoustag.outputs.tag }}
            - [ ] Feature 1
            - [ ] Feature 2
            - [ ] Feature 3
          draft: false
          prerelease: false
      
        
