# Build release

name: Build release


on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Get Latest Tag
        run: |
           git tag -a v0.0.4 -m "Version 0.0.4"
           echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          #  latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          #  echo "Latest Tag: $latest_tag"
          #  echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Use Latest Tag
        run: |
           echo "The latest tag is ${{ env.LATEST_TAG }}"

      # - name: Create a Release in a GitHub Action
      #   uses: comnoco/create-release-action@v2.0.5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
      
        
